databases:
  - name: theprettiestprice
    databaseName: theprettiestprice
    plan: free # make sure to set this to free or you'll get billed $$$
    user: theprettiestprice

services:
  - type: web
    name: theprettiestprice
    runtime: ruby
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: theprettiestprice
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
