databases:
  - name: the-prettiest-price
    databaseName: the-prettiest-price
    plan: free # make sure to set this to free or you'll get billed $$$
    user: the-prettiest-price

services:
  - type: web
    name: the-prettiest-price
    runtime: ruby
    env: ruby # this app is written in ruby
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: the-prettiest-price
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
